version: "3.9"

services:
    redis:
        image: redis:latest

    celery:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
            - redis
        volumes:
            - ./celery/celery/:/celery_app/celery/celery/
            - ./redis-py/redis/:/celery_app/redis-py/redis/
            - ./py-amqp/amqp/:/celery_app/py-amqp/amqp/
            - ./kombu/kombu/:/celery_app/kombu/kombu/
            - ./billiard/billiard/:/celery_app/billiard/billiard/
            - ./tasks.py:/celery_app/tasks.py

    celery-stats:
        build:
          context: .
          dockerfile: Dockerfile2
        depends_on:
            - redis
            - celery
        volumes:
            - ./celery/celery/:/celery_app/celery/celery/
            - ./py-amqp/amqp/:/celery_app/py-amqp/amqp/
            - ./kombu/kombu/:/celery_app/kombu/kombu/
            - ./billiard/billiard/:/celery_app/billiard/billiard/
            - ./stats.py:/celery_app/stats.py
            - ./tasks.py:/celery_app/tasks.py
