version: "3.9"

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 15672:15672
    celery:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
            - rabbitmq
